### ISSUE TITLE
gulp-gh-pages Error

### ISSUE THREAD

**Issue by minwe** [amazeui/gulp-tasks#1]
shinnn/gulp-gh-pages#42

```
git version 2.4.3
npm -v 3.1.2
node -v v0.12.7
```

```
~/Dev/AmazeUI/dialog/node_modules/when/lib/decorators/unhandledRejection.js:80
                throw e;
                      ^
Error: Error: Command failed: /bin/sh -c git rev-list --pretty=raw --max-count=1 
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=<n>
    --max-age=<epoch>
    --min-age=<epoch>
    --sparse
    --no-merges
    --min-parents=<n>
    --no-min-parents
    --max-parents=<n>
    --no-max-parents
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=<n> | --no-abbrev
    --abbrev-commit
    --left-right
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all

    at /Users/minwe/Dev/AmazeUI/dialog/node_modules/gulp-gh-pages/index.js:143:10
    at tryCatchReject (/Users/minwe/Dev/AmazeUI/dialog/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/minwe/Dev/AmazeUI/dialog/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/Users/minwe/Dev/AmazeUI/dialog/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/Users/minwe/Dev/AmazeUI/dialog/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/minwe/Dev/AmazeUI/dialog/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/minwe/Dev/AmazeUI/dialog/node_modules/when/lib/Scheduler.js:27:9)
    at process._tickCallback (node.js:355:11)
```

**Comment by minwe** [comment]
https://github.com/shinnn/gulp-gh-pages/issues/42#issuecomment-223530197

Just do:

```bash
rm -rf ./publish
```
